### PR TITLE
Address MSVC C4267 warnings

### PR DESCRIPTION
**Pull request by rozmansi**
Mostly, the warnings were false positives and were silenced using typecasting.

However, gzputs() did allow integer overflow when input string is longer than 2 Gi characters.

### CODE REVIEW

**Comment by rozmansi** [comment]
Wondering whether I should push this commit upstream to [madler/zlib](https://github.com/madler/zlib)?

**Comment by vadz** [comment]
Unfortunately the upstream doesn't seem to deal with PRs very expediently (last closed one was in July AFAICS), but they're still active, so it would indeed be worth at least trying to submit this there.

Generally speaking, we try to avoid diverging from the upstream unless absolutely necessary, so if they apply these changes, I'd be glad to merge them too (or rather merge the upstream version including them), but if not, it would be better to disable these warnings at make/project file level (as is already done, I believe, for some other warnings and 3rd party libraries). Unless the `gzputs()` is serious enough to warrant fixing it, but I don't know if it really is/can be?

**Comment by rozmansi** [comment]
Trying to make a PR upstream, I realized, Mark Adler already fixed all those in the `devel` branch. See the 793ad7f559555757e6443ea591ce70de5505fc69 and 90287635ef9ae8e51e120483d1b48789239a0577 commits.

So, I guess once Mark decides to make a release, this will be included.

**Comment by vadz** [comment]
I see, thanks. Maybe we could/should merge `upstream/develop` into our `wx` branch already? It seems to have quite a few fixes/improvements since almost 5 years...

**Comment by rozmansi** [comment]
Maybe Mr Adler has a reason to keep his `devel` and `master` branches separate? API/ABI or even data stream incompatibility? Or, lack of time or interest to finalize and release it? Just guessing.

Maybe stick with the `master` version until somebody comes up with a better argument to switch wxWidgets to `devel` other than just to silence some MSVC warnings. :)

**Pull request closed without merging**
